apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:B/pWN1gVYsWi17Q8W/HGVA==,iv:GdYQbY5jA+rspesa096Ro3ZJWYFFTqEelloKCnmwdXs=,tag:xxrmnazIw3amtfM1Q1J7rw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:6Ph4D8HUX5SrXUN4s5ygzS5HLANEqf6C9LacP7BICsgDMBUKsQ==,iv:Pe6nmoM51c9o6sXQBZsVJ71YWMYZPD6CjEGFBjW3E+M=,tag:oYGAZL/BchSU9ZRD+sZGrw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:d7ptSdHhDyxaXMqMk6YkPkbQ,iv:tQ54x14v9GcF7h4ZFokmsDV184aNEnu1ARZr0cwYC8g=,tag:68dROdk08HL3bHXAZmk2ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h9zj5zgleqep85uzhtvsdaudvn44n2rczhxlrthvupjnrk4scegs8hsz0m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWnVWOTZ1emR4TzFyL2ZN
            ZktMU0c5Q3dXZnYybTlVNG40YlVmdjB2NEZBClJjVlc1TjdXZVB1NkZ4Ri9hU3Ex
            VHl0ektWamhwV1R6ZnVOS1JMSXJ5NlkKLS0tIGlacHl5WGV3dmNVZTNON0Z0QTdx
            TXM5eEZwR1dCMkE0TzZQM3U4U1NRZ3cKxPpBSlkGoqJZuFbgENc9umg3rEVQxytn
            S8SBWIpADq4Kzn4uA2dumLKIa319aaWJh16M8f+ZnX/SRp84fVgK1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T04:37:04Z"
    mac: ENC[AES256_GCM,data:iH+VRLRXXGLVFjGYy5mSjiqzsnc+egnF0oOgOOvB5RsgEGqXaU5uCtJ33BUFOvdmLu+/mOXBN341qQduR1+FOFoGRl2Twz5kkB7O0U7UdQLZrIwwz7XD5/GzONXKhLS1/yRlal1thBaky+xJxH76JyhXjdHJKcx/Mv2o62Bv/uU=,iv:DwZVR5FXfZg5ytLbew62Rezv2qP2IfkIi2i8h4Ob21U=,tag:qZNq7wElF1oANc43DnS3VQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
