apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:PtJVL+1pCDYGYnqaH0kXb7+H5bxR9pA28hDzzCTnoPtwXH4jKSbVd9kqPdt8/8O5zdDateQAyxJnmgbN,iv:KZ/rYwpL+D4cqD0Fsnf30VdnuI/fyfHgyOvixsZPs1k=,tag:z0use8CyRuBaGSmSpUOy2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h9zj5zgleqep85uzhtvsdaudvn44n2rczhxlrthvupjnrk4scegs8hsz0m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOGY4cjB1MVBMb0VTNHpF
            SkhEbDN0bHdIOUMrQmh3R3FZempGMDVwWW5zCk1iRFhyRWJqaSs0UjFvM20yelI1
            MnhhTzlMcjdaMWhOQk1vNGF0dFdmWkkKLS0tIFh0N2xneU04VFVIejNydGNuSWIv
            K3FTQjE5U1J2OXhBV2NRMlZIUVdkODQKxJCyPCtVcjPp6V2jk0cutTWki/Yu2wPW
            oDjnHzGCqSA0W10pNVIzzjZ2zsJt94lE3Yfx07zY7wuUNvPaehXm1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T04:37:04Z"
    mac: ENC[AES256_GCM,data:y3QADCS9ypEvBuuC30E5/5yjGqydoiykhxy0AnJtGfOC0QjEsUFql2YmiPjzp7wjxAchsKHbrU5q/gay2RNxpTcO34rWbFlPfWFIWCVTUaXpFhSGZGsC7vfdAJlKkvEta4/ShpIStmn+aWMx4GfQlpJbm4u3NT3R/lPL7caXTLc=,iv:sblMrmvqAydbPmAYUIj8vvmIwMgznuxyLTXPjeWmBCU=,tag:PmKVxhXTeRIaGMllyYGA2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
