---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "172.16.150.170"
  METALLB_LB_RANGE: "172.16.150.180-172.16.150.190"
  METALLB_K8S_GATEWAY_ADDR: "172.16.150.180"
  METALLB_INGRESS_ADDR: "172.16.150.181"
